### ISSUE TITLE
Create a 0.1 tag for publishing to OPAM

### ISSUE THREAD

**Issue by tmcgilchrist** [didier-wenzek/ocaml-kafka#1]
Hey, I saw this project in r/ocaml and wanted to try it out. A quick `opam search` showed that this project isn't yet available there.

I was wondering if you consider this project to be worthy of a `0.1` version and would be happy to have it published on OPAM. I've done some of the initial legwork to create an opam package. To complete that I need a tag created in this repo as explained [here](https://github.com/OCamlPro/opam-publish#step-0-a-hosted-archive) which will create a tar.gz file for that version. 

After that I can create a PR against OPAM and get this project added there.

Cheers

**Comment by didier-wenzek** [comment]
Hi and thanks for your help.

Your offer is timely : the project is stable enough to be tested by 
others and I need feedbacks.
So I just created a release: 
https://github.com/didier-wenzek/ocaml-kafka/releases/tag/0.1.

Let me know if you have any issues or requests.

Br
Didier

**Comment by tmcgilchrist** [comment]
I think that's all I need to create an opam package, I'll link back here with the PR.

In the meantime I'll have a look through the code and write some tests.

Cheers

**Comment by didier-wenzek** [comment]
I just released a new 0.2 tag (with lwt support).

Have you any feedbacks about the code or the opam package ?

Cheers

**Comment by ygrek** [comment]
ocaml/opam-repository#4201

**Comment by tmcgilchrist** [comment]
@didier-wenzek apologies, this fell off my radar after switching jobs and finding I needed to tool up in Haskell. Good to see it's making it into opam

**Comment by didier-wenzek** [comment]
No problem, I'm quite busy too ! And glad to see coming the opam package. Thanks @ygrek !
