### ISSUE TITLE
Publish kafka_async

### ISSUE THREAD

**Issue by tecklund** [didier-wenzek/ocaml-kafka#22]
Are there plans to publish kafka_async? I'm going to have trouble convincing folks to pin an unpublished version of this library

**Comment by didier-wenzek** [comment]
Yes, I should have done it sooner but failed to find time and energy to work on it. I'm glad to learn that there are users and I will take the time to publish it in the first week of August. Do you have any feedback on the API?

**Comment by tecklund** [comment]
We are looking for a simple ocaml producer and this should work - my only concern is that there isn't a partitioner. Other than that, I like the simplicity of the API

**Comment by tecklund** [comment]
Hmm, i'm seeing some strange behavior:

I would have expected this 

```
let producer = Kafka.new_producer [
  "metadata.broker.list", "localhost:9092";
  "acks", "all"
  ];;
let producer_topic = Kafka.new_topic producer "test" ["message.timeout.ms","10000"];;

let partition = 0;;
let timeout_ms = 1000;;

Kafka.produce producer_topic partition "message 0";;
Kafka.produce producer_topic partition "message 1";;
Kafka.produce producer_topic partition "message 2";;

Kafka.destroy_topic producer_topic;;
Kafka.destroy_handler producer;;

print_endline "Program complete"
```
to produce three messages, but it looks like the program exits before anything is written. Adding
```
Unix.sleep 5;;
```
lets the producer succeed before exiting, but I would have expected `"acks", "all"` to make writing synchronous. 

Also, while testing against a local kafka everything is fine, but against my MSK cluster (2.4.1) the producer completes without error, but no messages are added to the topic.

**Comment by didier-wenzek** [comment]
About the issues producing messages before the program exit.

The correct way to wait that all the messages have been actually produced is to invoke [`Kafka.wait_delivery](https://github.com/didier-wenzek/ocaml-kafka/blob/master/lib/kafka.mli#L163). Setting a [delivery callback](https://github.com/didier-wenzek/ocaml-kafka/blob/master/lib/kafka.mli#L91) can also be used to follow delivery on a message basis (assuming the messages have an [id assigned when produced](https://github.com/didier-wenzek/ocaml-kafka/blob/master/lib/kafka.mli#L133)).

Note that the messages are buffered when sent to Kafka, waiting up to `queue.buffering.max.ms` milliseconds to batch `batch.num.messages` messages.

**Comment by didier-wenzek** [comment]
Opam PR https://github.com/ocaml/opam-repository/pull/16994

**Comment by Leonidas-from-XIV** [comment]
That's a great development, we have an internal fork of the library that we only use to publish interim releases to our internal opam-repository so having it released in public is a great improvement.

**Comment by tecklund** [comment]
Awesome, thank you!
