### ISSUE TITLE
job_consume leak

### ISSUE THREAD

**Issue by ygrek** [didier-wenzek/ocaml-kafka#7]
```
extern CAMLprim
value ocaml_kafka_consume_job(value caml_kafka_topic, value caml_kafka_partition, value caml_kafka_timeout)
{
  struct job_consume* job = (struct job_consume*)lwt_unix_new(struct job_consume);
```
but there is no corresponding `free` afaics?

**Comment by didier-wenzek** [comment]
Here, I need some help. I'm not aware of a call pending to lwt_unix_new.

The lwt documentation provides an example to wrap `mkdir`. This example introduces two allocations (`lwt_unix_new` and `lwt_unix_alloc_job`) a single release function (`lwt_unix_free_job`).

**Comment by ygrek** [comment]
I guess lwt framework relies on `job` object which keeps state of job to have `lwt_unix_job` as first member, thus acting as an "extension".

**Comment by didier-wenzek** [comment]
Thanks these clarifications.
